spring.datasource.url=jdbc:mariadb://mariadb-service:3306/wielkie_akcje_i_transakcje?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=student
spring.datasource.password=wcy
spring.jpa.hibernate.ddl-auto=update