spring.datasource.url=jdbc:mariadb://10.6.57.163:3306/wielkie_akcje_i_transakcje?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=student
spring.datasource.password=wcy